#!/usr/bin/env python3
#coding: utf-8

############################################
#                MATHEMATICS               #
############################################
#                                          #
#  MONFA-MATAS Patricica & ROZET Corentin  #
#                                          #
#            Project : 205IQ_2019          #
#                                          #
############################################

from sys import argv

from usage import help
from checkArgs import ArgumentManager
from IQ import IQ


def main():

    argsManager = ArgumentManager()

    if argsManager.needHelp(argv):
        help()
    elif argsManager.checkArgs(argv) == 84:
        exit (84)
    else:
        iq = IQ()
        iq.run()


if __name__ == "__main__":
    main()
