# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test compilation
      run: make re && make fclean
    - name: Push to Epitech repo
      run: |
        ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
        git remote update
        git fetch
        git push --repo="git@git.epitech.eu:/corentin.rozet@epitech.eu/205IQ_2019" --force
